# Generated by Django 2.2.2 on 2019-10-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamestatus_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatus',
            old_name='user_id',
            new_name='user',
        ),
    ]
