# Generated by Django 2.2.2 on 2019-11-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191103_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatus',
            name='coin',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='doubleUpCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
