# Generated by Django 2.2.2 on 2019-11-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20191103_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatus',
            old_name='currentMark',
            new_name='current_mark',
        ),
        migrations.RenameField(
            model_name='gamestatus',
            old_name='doubleUpCount',
            new_name='double_up_count',
        ),
        migrations.RenameField(
            model_name='gamestatus',
            old_name='gainedCoin',
            new_name='gained_coin',
        ),
        migrations.RenameField(
            model_name='gamestatus',
            old_name='targetMark',
            new_name='target_mark',
        ),
    ]
